apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal-communication
  namespace: datauniverse-dev
spec:
  podSelector:
    matchLabels:
      app: datauniverse-app
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: datauniverse-dev
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: datauniverse-dev
    ports:
    - protocol: TCP
      port: 6379 