apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: datauniverse-rolebinding
  namespace: datauniverse-dev
subjects:
- kind: ServiceAccount
  name: datauniverse-service-account
  namespace: datauniverse-dev
roleRef:
  kind: Role
  name: datauniverse-role
  apiGroup: rbac.authorization.k8s.io 