apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: datauniverse-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
        cluster: https://kubernetes.default.svc
      - env: staging
        cluster: https://kubernetes.default.svc
      - env: prod
        cluster: https://kubernetes.default.svc
  template:
    metadata:
      name: 'datauniverse-app-{{env}}'
    spec:
      project: default
      source:
        repoURL: git@github.com/TariqTTO/DevGitOps.git
        #!# targetRevision: HEAD
        targetRevision: init-tto/gitops
        path: 'apps/{{env}}'
      destination:
        server: '{{cluster}}'
        namespace: 'datauniverse-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true