apiVersion: v1
kind: Service
metadata:
  name: datauniverse-service
  labels:
    app: datauniverse-app
spec:
  selector:
    app: datauniverse-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP